colrev\_core.review\_dataset.OriginError
========================================

.. currentmodule:: colrev_core.review_dataset

.. autoexception:: OriginError
