colrev\_core.review\_dataset.FieldError
=======================================

.. currentmodule:: colrev_core.review_dataset

.. autoexception:: FieldError
