colrev\_core.review\_dataset.RecordNotInRepoException
=====================================================

.. currentmodule:: colrev_core.review_dataset

.. autoexception:: RecordNotInRepoException
